---
version: '3'

services:
  nginx-test:
    image: nginx-test:latest
    restart: always
    ports:
      - "81:80"
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.docker.nas`)"
    healthcheck:
      test: ["CMD", "nc" ,"-z", "127.0.0.1", "80"]
      interval: 15s
